export const ACTIONS = {
    ADD_PLAYER: 'ADD_PLAYER',
    DELETE_USER: 'DELETE_USER',
    NEXT_STATE: 'NEXT_STATE',
};

export const PLAYER_STATE = {
    IN_LOBBY: 'IN_LOBBY',
    VOTING: 'VOTING',
    WAITING_RESULT: 'WAITING_RESULT',
    ON_RESULT: 'ON_RESULT',
};
